version: "3"

services:
  # clients:
  #   build: .
  #   entrypoint: wait-for db:3306 -t 40 -- sh -c "npm install && npm run start:dev"
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/home/node/app

  # clients_db:
  #   build: mysql
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ./.docker/dbdata:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=clients
  #     - MYSQL_ROOT_PASSWORD=root

  # accounts:
  #   build: .
  #   entrypoint: wait-for db:3306 -t 40 -- sh -c "npm install && npm run start:dev"
  #   ports:
  #     - 3001:3001
  #   volumes:
  #     - .:/home/node/app

  # accounts_db:
  #   build: mysql
  #   restart: always
  #   tty: true
  #   volumes:
  #     - ./.docker/dbdata:/var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=accounts
  #     - MYSQL_ROOT_PASSWORD=root

  zookeeper:
    image: "bitnami/zookeeper:3"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:2"
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
